<a href="https://colab.research.google.com/github/Prabhat7867/Compiler-Design-Lab/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
ls=[10,20,30,40]
a=np.array(ls)
print(a)

[10 20 30 40]


In [7]:
import numpy as np
np.arange(2,32,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30])

In [9]:
import numpy as np
ls=[10,20,30,40]
np.linspace(3,6,4)

array([3., 4., 5., 6.])

In [12]:
np.arange(24).reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
np.arange(24).reshape(2,2,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [14]:
a=np.arange(24).reshape(2,2,2,3)
print(a)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


In [16]:
a.size

24

In [17]:
a.shape

(2, 2, 2, 3)

In [20]:
a.ndim

4

In [21]:
np.random.randint(2,9,20)

array([2, 6, 7, 7, 6, 6, 4, 8, 7, 3, 2, 2, 6, 7, 5, 8, 8, 5, 6, 6])

In [24]:
np.random.randint(2,9,(20,3))

array([[2, 3, 4],
       [6, 5, 2],
       [7, 8, 6],
       [8, 5, 4],
       [8, 7, 7],
       [2, 4, 5],
       [6, 3, 3],
       [5, 4, 7],
       [3, 3, 5],
       [7, 5, 6],
       [3, 6, 8],
       [2, 3, 8],
       [5, 4, 3],
       [4, 4, 5],
       [3, 5, 2],
       [4, 5, 3],
       [6, 7, 7],
       [3, 4, 7],
       [6, 5, 5],
       [6, 5, 2]])

In [28]:
np.random.randint(2,9,(2,3,4,5))

array([[[[3, 5, 5, 2, 5],
         [6, 2, 2, 2, 2],
         [7, 3, 6, 6, 3],
         [3, 8, 3, 3, 7]],

        [[8, 5, 5, 7, 6],
         [8, 2, 2, 5, 3],
         [7, 8, 6, 6, 6],
         [5, 7, 2, 3, 6]],

        [[5, 5, 8, 5, 2],
         [8, 7, 7, 6, 2],
         [5, 4, 5, 6, 2],
         [7, 5, 7, 2, 6]]],


       [[[7, 5, 5, 7, 2],
         [3, 7, 5, 2, 2],
         [3, 6, 8, 7, 2],
         [8, 4, 6, 4, 2]],

        [[3, 5, 3, 2, 5],
         [8, 6, 4, 8, 2],
         [6, 7, 3, 2, 3],
         [5, 8, 6, 5, 4]],

        [[7, 7, 8, 5, 5],
         [3, 2, 2, 5, 5],
         [4, 2, 8, 2, 8],
         [3, 2, 7, 8, 8]]]])